os: Visual Studio 2015
version: '{branch}-{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.13"
      PYTHON_ARCH: "32"

      GETH_VER: geth-windows-386-1.5.5-ff07d548
      IPFS_VER: go-ipfs_v0.4.4_windows-386
      OPENSSL_VER: openssl-1.0.2j-i386-win32

      OPENSSL_DIR: C:\OpenSSL
      GETH_DIR: C:\%GETH_VER%
      IPFS_DIR: C:\go-ipfs
      WHEELS_DIR: C:\wheels

      WHEEL_PYQT4: PyQt4-4.11.4-cp27-none-win32.whl
      WHEEL_OPENEXR: OpenEXR-1.2.0-cp27-none-win32.whl
      WHEEL_PYETHASH: pyethash-0.1.23-cp27-cp27m-win32.whl
      WHEEL_SECP256K1: secp256k1-0.13.2-cp27-cp27m-win32.whl

      WHEELS_URL: https://github.com/golemfactory/golem/wiki/wheels

cache:
  - '%OPENSSL_DIR%            -> appveyor.yml'
  - '%IPFS_DIR%               -> appveyor.yml'
  - '%GETH_DIR%               -> appveyor.yml'
  - '%WHEELS_DIR%             -> requirements.txt'
  - '%APPDATA%\pip\Cache      -> requirements.txt'
  - C:\ProgramData\chocolatey -> appveyor.yml

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%OPENSSL_DIR%;%GETH_DIR%;%IPFS_DIR%;%PATH%
  # docker
  - choco install -y virtualbox
  - choco install -y docker-machine
  - docker-machine.exe create -d virtualbox default
  - docker-machine.exe env default

  # ssl
  - cmd:|
      if not exist %OPENSSL_DIR% (
        appveyor DownloadFile https://indy.fulgan.com/SSL/%OPENSSL_VER%.zip &&
        7z x %OPENSSL_VER%.zip -y -ao C:\OpenSSL > NUL
      )

  # geth
  - cmd:|
      if not exist %GETH_DIR% (
        appveyor DownloadFile https://gethstore.blob.core.windows.net/builds/%GETH_VER%.zip &&
        7z x %GETH_VER%.zip -y -ao C:\ > NUL
      )

  # ipfs
  - cmd:|
      if not exist %IPFS_DIR% (
        appveyor DownloadFile https://dist.ipfs.io/go-ipfs/v0.4.4/%IPFS_VER%.zip &&
        7z x %IPFS_VER%.zip -y -ao C:\ > NUL
      )
  - ipfs init
  - ps: $IPFSProcess = Start-Process ipfs.exe -PassThru

  # pip
  - pip install --disable-pip-version-check --user --upgrade pip

  # prebuilt packages
  - cmd: if not exist %WHEELS_DIR% mkdir %WHEELS_DIR%
  - cmd:|
      if not exist %WHEELS_DIR%\%WHEEL_PYQT4% (
        curl -fsS -o %WHEELS_DIR%\%WHEEL_PYQT4% %WHEELS_URL%/%WHEEL_PYQT4% &&
        pip install %WHEELS_DIR%\%WHEEL_PYQT4%
      )
  - cmd:|
      if not exist %WHEELS_DIR%\%WHEEL_OPENEXR% (
        curl -fsS -o %WHEELS_DIR%\%WHEEL_OPENEXR% %WHEELS_URL%/%WHEEL_OPENEXR% &&
        pip install %WHEELS_DIR%\%WHEEL_OPENEXR%
      )
  - cmd:|
      if not exist %WHEELS_DIR%\%WHEEL_PYETHASH% (
        curl -fsS -o %WHEELS_DIR%\%WHEEL_PYETHASH% %WHEELS_URL%/%WHEEL_PYETHASH% &&
        pip install %WHEELS_DIR%\%WHEEL_PYETHASH%
      )
  - cmd:|
      if not exist %WHEELS_DIR%\%WHEEL_SECP256K1% (
        curl -fsS -o %WHEELS_DIR%\%WHEEL_SECP256K1% %WHEELS_URL%/%WHEEL_SECP256K1% &&
        pip install %WHEELS_DIR%\%WHEEL_SECP256K1%
      )

  # requirements
  - pip install -r requirements.txt
  - pip install pytest mock coverage
  - python setup.py develop

test_script:
  - python setup.py test

on_finish:
  - ps: Stop-Process -Id $IPFSProcess.Id
